In [47]:
# requests.get() → baixou a página
# pagina.text → pegou o HTML
# StringIO() → transformou em "arquivo"
# pd.read_html() → leu as tabelas

import pandas as pd
import requests
from io import StringIO

URL = "https://pt.wikipedia.org/wiki/Lista_das_maiores_empresas_do_Brasil"

headers = {
    "User-Agent": "Mozilla/5.0"
}

pagina = requests.get(URL, headers=headers)

tabelas = pd.read_html(StringIO(pagina.text))

tabelas

[     #  Forbes Global 2000                Nome  Receita (em bilhões de US$)  \
 0    1                  58           Petrobras                        12417
 1    2                  98       Itaú Unibanco                         5317
 2    3                 139                Vale                         4143
 3    4                 171     Banco do Brasil                         5398
 4    5                 173            Bradesco                         5626
 5    6                 372         BTG Pactual                         1549
 6    7                 563                 JBS                         7258
 7    8                 774              Suzano                          996
 8    9                 928          Eletrobras                          679
 9   10                 980              Gerdau                          157
 10  11                1015             Marfrig                         2529
 11  12                1026              Itaúsa                          164
 12  13                1223                 WEG                          597
 13  14                1296              Raízen                         4731
 14  15                1398  Metalúrgica Gerdau                          157
 15  16                1436                  B3                          176
 16  17                1574       Vibra Energia                         3513
 17  18                1602             Braskem                         3513
 18  19                1668        CPFL Energia                         1869
 19  20                1679         Grupo Ultra                         2767
 20  21                1974               Cosan                          769

     Lucro (em bilhões de US$)  Ativos (em bilhões de US$)  \
 0                        3647                        1849
 1                         575                        4414
 2                        1598                        8772
 3                         576                       38027
 4                         349                       35745
 5                         152                        8535
 6                         299                        3942
 7                         355                         267
 8                          70                        5118
 9                         227                        1494
 10                         80                        2578
 11                        265                         183
 12                         89                          57
 13                        187                         199
 14                         75                        1514
 15                         82                         921
 16                          3                         792
 17                         -6                        1668
 18                         99                        1347
 19                         31                         669
 20                         23                        2547

     Valor (em bilhões de US$)                         Setor
 0                        6303                Petróleo e gás
 1                        5128                      Bancário
 2                        6172                     Mineração
 3                        2485                      Bancário
 4                         316                      Bancário
 5                        5077                      Bancário
 6                         816                   Alimentação
 7                        1095              Papel e celulose
 8                        1728                       Energia
 9                         873                    Siderurgia
 10                        894                   Alimentação
 11                       1707                 Investimentos
 12                       3313                   Eletrônicos
 13                        681                       Energia
 14                        239                    Siderurgia
 15                       1384                      Finanças
 16                        309                Petróleo e gás
 17                        381                  Petroquímico
 18                        722             Utilidade pública
 19                        361  Distribuição de combustíveis
 20                        555                       Energia  ,
    Classificação  Fortune 500                     Nome              Indústria  \
 0              1           71                Petrobras             Óleo e gás
 1              2          177                 JBS S.A.  Produção de alimentos
 2              3          207      Banco Itaú Unibanco               Bancário
 3              4          251          Banco do Brasil               Bancário
 4              5          273           Banco Bradesco               Bancário
 5              6          301                   Raízen                Energia
 6              7          332                     Vale              Mineração
 7              8          406  Caixa Econômica Federal                Finança
 8              9          429            Vibra Energia             Óleo e gás

    Receita (milhões de dólares)  Lucros (milhões de dólares  Funcionários  \
 0                        124474                       36623         45149
 1                         72626                        2995        260000
 2                         63884                        5755        101094
 3                         55870                        5353         85953
 4                         51587                        4066         81222
 5                         47721                         474         44738
 6                         44287                       18788         64516
 7                         37066                        1894         86959
 8                         35155                         298          7777

              Sede
 0  Rio de Janeiro
 1       São Paulo
 2       São Paulo
 3        Brasília
 4          Osasco
 5       São Paulo
 6  Rio de Janeiro
 7        Brasília
 8  Rio de Janeiro  ,
    Classificação  Fortune 500                     Nome              Indústria  \
 0              1           74                Petrobras             Óleo e gás
 1              2          191      Banco Itaú Unibanco               Bancário
 2              3          219                   JBS SA  Produção de alimentos
 3              4          221           Banco Bradesco               Bancário
 4              5          269          Banco do Brasil               Bancário
 5              6          305  Caixa Econômica Federal                Finança
 6              7          336                     Vale              Mineração
 7              8          499                 Ultrapar           Conglomerado

    Receita (milhões de dólares)  Lucros (milhões de dólares)  Funcionários  \
 0                        95.584                        7.173        63.361
 1                        54.662                        6.815       100.335
 2                        49.709                        6.900       230.086
 3                        49.612                        4.538        86.772
 4                        43.333                        3.783        96.889
 5                        40.240                        2.833        84.952
 6                        36.696                        6.860        70.270
 7                        24.816                      315.000        17.034

              Sede
 0  Rio de Janeiro
 1       São Paulo
 2       São Paulo
 3          Osasco
 4        Brasília
 5        Brasília
 6  Rio de Janeiro
 7       São Paulo  ,
     Rank  Forbes 2000                            Nome            Sede  \
 0      1           50                       Petrobras  Rio de Janeiro
 1      2           58             Banco Itaú Unibanco       São Paulo
 2      3           96                  Banco Bradesco          Osasco
 3      4          139                            Vale  Rio de Janeiro
 4      5          154                 Banco do Brasil        Brasília
 5      6          657                      Eletrobras  Rio de Janeiro
 6      7          825                        JBS S.A.       São Paulo
 7      8          859                          Itaúsa       São Paulo
 8      9          912                         Braskem       São Paulo
 9     10         1089                              Oi  Rio de Janeiro
 10    11         1429  Companhia Siderúrgica Nacional       São Paulo
 11    12         1478                      Cielo S.A.         Barueri
 12    13         1486                              B3       São Paulo
 13    14         1546                    CPFL Energia        Campinas
 14    15         1647                        Ultrapar       São Paulo
 15    16         1660                             GPA       São Paulo
 16    17         1736              Metalurgica Gerdau    Porto Alegre
 17    18         1799         Suzano Papel e Celulose        Salvador
 18    19         1836                           CEMIG  Belo Horizonte
 19    20         1865                          Sabesp       São Paulo

     Receita (bilhões US$)  Lucros (bilhões US$)  Ativos (bilhões US$)  \
 0                    95.7                   7.1                 222.0
 1                    53.8                   6.8                 383.2
 2                    62.6                   5.2                 332.1
 3                    36.8                   7.0                  88.2
 4                    42.0                   3.8                 368.4
 5                     6.9                   3.6                  46.8
 6                    49.7                   0.0                  29.5
 7                     1.6                   2.6                  16.3
 8                    15.9                   0.8                  15.3
 9                     6.0                   6.7                  16.9
 10                    6.3                   1.4                  12.2
 11                    3.2                   0.9                  21.3
 12                    1.3                   0.6                  10.1
 13                    8.2                   0.5                  11.2
 14                   24.8                   0.3                   7.9
 15                   13.5                   0.3                  13.6
 16                   12.6                   0.2                  13.2
 17                    3.7                   0.1                  13.9
 18                    6.1                   0.5                  15.4
 19                    4.4                   0.8                  11.2

     Valor (bilhões US$)              Industria
 0                  91.2         Petróleo e gás
 1                  80.8               Bancário
 2                  70.7               Bancário
 3                  68.3                 Mining
 4                  34.5               Bancário
 5                  11.1                Energia
 6                  12.3  Produção de alimentos
 7                  24.7           Conglomerado
 8                   9.7            Oil and Gas
 9                   2.5       Telecomunicações
 10                  5.3                    Aço
 11                  5.7               Finanças
 12                 16.5               Finanças
 13                  7.4                Energia
 14                  6.2           Conglomerado
 15                  6.3                 Varejo
 16                  1.8                    Aço
 17                 14.0       Papel e celulose
 18                  6.1                Energia
 19                  7.2      Saneamento Básico  ,
                      vdeEconomia do Brasil  \
 0                                    Geral
 1                                 História
 2                                    Fases
 3                                  Setores
 4                   Planejamento Econômico
 5                                  Setores
 6                       Economia  regional
 7                                  Regiões
 8                    Unidades  federativas
 9                              Indicadores
 10  Categoria  Portal da Economia  Commons

                               vdeEconomia do Brasil.1
 0   Crises econômicas Divisão geoeconômica Gestão ...
 1   Fases Ciclo do pau-brasil Ciclo do açúcar Drog...
 2   Ciclo do pau-brasil Ciclo do açúcar Drogas do ...
 3              Agricultura Industrialização Mineração
 4   Pré-1950 Encilhamento PEOP POE 1950-94 SALTE M...
 5   Agricultura e agronegócio Armazenagem Irrigaçã...
 6   Regiões Centro-Oeste Nordeste Norte Sudeste Su...
 7             Centro-Oeste Nordeste Norte Sudeste Sul
 8   Acre Alagoas Amapá Amazonas Bahia Ceará Distri...
 9   Balança Comercial Desemprego Dívida pública Ex...
 10             Categoria  Portal da Economia  Commons  ,
          0                                                  1
 0    Fases  Ciclo do pau-brasil Ciclo do açúcar Drogas do ...
 1  Setores             Agricultura Industrialização Mineração,
                        0                                                  1
 0                Regiões            Centro-Oeste Nordeste Norte Sudeste Sul
 1  Unidades  federativas  Acre Alagoas Amapá Amazonas Bahia Ceará Distri...]

In [48]:
# len é para ver o comprimento da tabela 
# aqui ele trouxe uma resposta que encontrou 7 tabelas 
len(tabelas)

7

In [49]:
# aqui a gente pegou a primeira tabela queé a zero porque no Python começa a contagem do zero
tabelas[0]

,#,Forbes Global 2000,Nome,Receita (em bilhões de US$),Lucro (em bilhões de US$),Ativos (em bilhões de US$),Valor (em bilhões de US$),Setor
0,1,58,Petrobras,12417,3647,1849,6303,Petróleo e gás
1,2,98,Itaú Unibanco,5317,575,4414,5128,Bancário
2,3,139,Vale,4143,1598,8772,6172,Mineração
3,4,171,Banco do Brasil,5398,576,38027,2485,Bancário
4,5,173,Bradesco,5626,349,35745,316,Bancário
5,6,372,BTG Pactual,1549,152,8535,5077,Bancário
6,7,563,JBS,7258,299,3942,816,Alimentação
7,8,774,Suzano,996,355,267,1095,Papel e celulose
8,9,928,Eletrobras,679,70,5118,1728,Energia
9,10,980,Gerdau,157,227,1494,873,Siderurgia
10,11,1015,Marfrig,2529,80,2578,894,Alimentação
11,12,1026,Itaúsa,164,265,183,1707,Investimentos
12,13,1223,WEG,597,89,57,3313,Eletrônicos
13,14,1296,Raízen,4731,187,199,681,Energia
14,15,1398,Metalúrgica Gerdau,157,75,1514,239,Siderurgia
15,16,1436,B3,176,82,921,1384,Finanças
16,17,1574,Vibra Energia,3513,3,792,309,Petróleo e gás
17,18,1602,Braskem,3513,-6,1668,381,Petroquímico
18,19,1668,CPFL Energia,1869,99,1347,722,Utilidade pública
19,20,1679,Grupo Ultra,2767,31,669,361,Distribuição de combustíveis
20,21,1974,Cosan,769,23,2547,555,Energia

In [50]:
df_forbes_2000 = tabelas[0]

df_forbes_2000 = df_forbes_2000.drop(columns=["#"])

df_forbes_2000

,Forbes Global 2000,Nome,Receita (em bilhões de US$),Lucro (em bilhões de US$),Ativos (em bilhões de US$),Valor (em bilhões de US$),Setor
0,58,Petrobras,12417,3647,1849,6303,Petróleo e gás
1,98,Itaú Unibanco,5317,575,4414,5128,Bancário
2,139,Vale,4143,1598,8772,6172,Mineração
3,171,Banco do Brasil,5398,576,38027,2485,Bancário
4,173,Bradesco,5626,349,35745,316,Bancário
5,372,BTG Pactual,1549,152,8535,5077,Bancário
6,563,JBS,7258,299,3942,816,Alimentação
7,774,Suzano,996,355,267,1095,Papel e celulose
8,928,Eletrobras,679,70,5118,1728,Energia
9,980,Gerdau,157,227,1494,873,Siderurgia
10,1015,Marfrig,2529,80,2578,894,Alimentação
11,1026,Itaúsa,164,265,183,1707,Investimentos
12,1223,WEG,597,89,57,3313,Eletrônicos
13,1296,Raízen,4731,187,199,681,Energia
14,1398,Metalúrgica Gerdau,157,75,1514,239,Siderurgia
15,1436,B3,176,82,921,1384,Finanças
16,1574,Vibra Energia,3513,3,792,309,Petróleo e gás
17,1602,Braskem,3513,-6,1668,381,Petroquímico
18,1668,CPFL Energia,1869,99,1347,722,Utilidade pública
19,1679,Grupo Ultra,2767,31,669,361,Distribuição de combustíveis
20,1974,Cosan,769,23,2547,555,Energia

In [51]:
# TRABALHANDO COM OS DADOS 

df_forbes_2000.columns = df_forbes_2000.columns.str.replace(r"(em bilhões de US$)", "")
df_forbes_2000.columns

Index(['Forbes Global 2000', 'Nome', 'Receita ', 'Lucro ', 'Ativos ', 'Valor ',
       'Setor'],
      dtype='str')

In [52]:
df_forbes_2000

,Forbes Global 2000,Nome,Receita,Lucro,Ativos,Valor,Setor
0,58,Petrobras,12417,3647,1849,6303,Petróleo e gás
1,98,Itaú Unibanco,5317,575,4414,5128,Bancário
2,139,Vale,4143,1598,8772,6172,Mineração
3,171,Banco do Brasil,5398,576,38027,2485,Bancário
4,173,Bradesco,5626,349,35745,316,Bancário
5,372,BTG Pactual,1549,152,8535,5077,Bancário
6,563,JBS,7258,299,3942,816,Alimentação
7,774,Suzano,996,355,267,1095,Papel e celulose
8,928,Eletrobras,679,70,5118,1728,Energia
9,980,Gerdau,157,227,1494,873,Siderurgia
10,1015,Marfrig,2529,80,2578,894,Alimentação
11,1026,Itaúsa,164,265,183,1707,Investimentos
12,1223,WEG,597,89,57,3313,Eletrônicos
13,1296,Raízen,4731,187,199,681,Energia
14,1398,Metalúrgica Gerdau,157,75,1514,239,Siderurgia
15,1436,B3,176,82,921,1384,Finanças
16,1574,Vibra Energia,3513,3,792,309,Petróleo e gás
17,1602,Braskem,3513,-6,1668,381,Petroquímico
18,1668,CPFL Energia,1869,99,1347,722,Utilidade pública
19,1679,Grupo Ultra,2767,31,669,361,Distribuição de combustíveis
20,1974,Cosan,769,23,2547,555,Energia